### ISSUE TITLE
AlertView rotation issue 

### ISSUE THREAD

**Issue by jojonarte** [wimagguc/ios-custom-alertview#113]
I'm having an issue with the alertView shadow. Upon rotating the tab I would get this screens below:
ORIGINAL ORIENTATION UPON TRIGGERING ALERT:
![image](https://cloud.githubusercontent.com/assets/11880365/25264531/40e6aee4-269a-11e7-8864-08657b74f6dd.png)
ROTATING LANDSCAPE:
![image](https://cloud.githubusercontent.com/assets/11880365/25264537/45ee2a7a-269a-11e7-8300-c0ca0330921d.png)
ROTATING BACK TO PORTRAIT:
![image](https://cloud.githubusercontent.com/assets/11880365/25264543/4a09e4aa-269a-11e7-9f6f-d55a8db47c56.png)

The shadow seems to not properly rotate with the orientation.

**Comment by timeflying** [comment]
Could you tell me how you fix this issue?

**Comment by timeflying** [comment]
If you remove the launch screen , the problem  is gone.

**Comment by timeflying** [comment]
PR #103  solve this bug
