### ISSUE TITLE
Alertview Rotation issue from Landscape to Portrait while key board is open

### ISSUE THREAD

**Issue by shahshrenik** [wimagguc/ios-custom-alertview#45]
There is one major bug in the code. While I am running an app in iPad Landscape mode , having a  keyboard opened (Say I am editing in textfield) , now if Alert is popped-up ... And I am rotating my iPad from Landscape to portrait mode at that time alertView's position is changing . Its a strange behaviour. Please update.
![ios simulator screen shot 06-jun-2014 4 37 33 pm](https://cloud.githubusercontent.com/assets/1861186/3199564/d1e64cfe-ed6a-11e3-9ed1-577ef454ecec.png)

**Comment by wimagguc** [comment]
Rotation should be sorted for IOS8+ and IOS7. I'm closing the related issues now, please reopen a new one if necessary.
