### ISSUE TITLE
Orientation is very bad for iPad(iOS8)

### ISSUE THREAD

**Issue by swalehapatanwala** [wimagguc/ios-custom-alertview#50]
I have tried the demo app in iPad mini. The background view doesn't change its frame on orientation change and also the alertview shows wrong orientation

**Comment by rosano** [comment]
+1

@russellbstephens thanks! works for me

**Comment by wimagguc** [comment]
Rotation should be sorted for IOS8+ and IOS7. I'm closing the related issues now, please reopen a new one if necessary.
