### ISSUE TITLE
Support for cocoapods?

### ISSUE THREAD

**Issue by jmartos89** [wimagguc/ios-custom-alertview#52]
I'm trying to install it using cocoapods but can not find a specification for this library: 

I leave my PODFILE: 

platform: ios, '7.0' 
pod "CustomIOS7AlertView", "~> 0.81"

thanks!

**Comment by osrl** [comment]
hello @wimagguc is there a good reason why you don't add support for cocoapods?

**Comment by thomasaw** [comment]
I would also be interested in Cocoapod support.

**Comment by wimagguc** [comment]
Cocoapods are finally supported! You can this class by: `pod "CustomIOSAlertView", "~> 0.9.1"`
