### ISSUE TITLE
iOS8 Alertview Rotation Issue

### ISSUE THREAD

**Issue by shahshrenik** [wimagguc/ios-custom-alertview#59]
![landscape ipad](https://cloud.githubusercontent.com/assets/1861186/5586451/0d87d444-90f4-11e4-9be2-f99f55df6ba0.png)
![portrait ipad](https://cloud.githubusercontent.com/assets/1861186/5586452/0dad85fe-90f4-11e4-9cbf-27babc8487c2.png)

Hello,

I am still facing rotation issue in iPad 2.0 with iOS 8.0. I m sure iPad mini will have still the same issue

See the images..Issues is in Landscape orientations.. AlertView's background is not getting resized and hence Alert is not displayed in the centre.

If I open an alert in Portrait mode, and change device's orientation to Landscape, at that time there is some problem in resizing the screenSize. And due to this , Alert is not displayed in the center of the screen

Have to modify the orientationDidChange code as it is only working currently with OS 7.1 or lower version. Transformation is not handled properly

**Comment by WizKIDz** [comment]
still problems... even with iPhone... good control though. id love to use it in an upcoming app with this issue fixed

**Comment by anandgupadhyay** [comment]
I have solved this issue, for my code, just set parentview property of alertview.
and 
use new screen size for ioS8 
add below code to class and use it instead of  [UIScreen mainscreen].bounds.size

+ (CGSize)screenSize {
    CGSize screenSize = [UIScreen mainScreen].bounds.size;
    if ((NSFoundationVersionNumber <= NSFoundationVersionNumber_iOS_7_1) && UIInterfaceOrientationIsLandscape([UIApplication sharedApplication].statusBarOrientation)) {
        return CGSizeMake(screenSize.height, screenSize.width);
    }
    return screenSize;
}

and remove code from height and width exchange code from countScreenSize and keyboardWillShow method.

Thats it

**Comment by wimagguc** [comment]
Rotation should be sorted for IOS8+ and IOS7. I'm closing the related issues now, please reopen a new one if necessary.
