### ISSUE TITLE
podfile ?

### ISSUE THREAD

**Issue by Jules2010** [wimagguc/ios-custom-alertview#67]
Can't see this on cocoapods.org

Tried...
pod 'CustomIOSAlertView', '~> 0.9.2'

I get the following error?

[!] Unable to satisfy the following requirements:

- `CustomIOSAlertView (~> 0.9.2)` required by `Podfile`
- `CustomIOSAlertView (~> 0.9.2)` required by `Podfile`

**Comment by Jules2010** [comment]
OK, tried this..

pod 'CustomIOSAlertView', '~> 0.9.2', :git => 'https://github.com/wimagguc/ios-custom-alertview.git'

But I get this...
[!] A dependency with an external source may not specify version requirements (CustomIOSAlertView).

**Comment by Jules2010** [comment]
I've also tried, which doesn't change things...

pod 'CustomIOSAlertView', '~> 0.9.2', :git => 'https://github.com/wimagguc/ios-custom-alertview.git', :podspec => 'https://github.com/wimagguc/ios-custom-alertview/blob/master/CustomIOSAlertView.podspec'

**Comment by Jules2010** [comment]
Hmmmm 0.9.1 works, but not 0.9.2

pod "CustomIOSAlertView", "~> 0.9.1"

**Comment by wimagguc** [comment]
Thanks for seeing this. CocoaPods doesn't seem to have picked up 0.9.2, but I just added a new tag with version 0.9.3 and that works for me:
`pod "CustomIOSAlertView", "~> 0.9.3"`
