### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by lupugabriel** [wimagguc/ios-custom-alertview#68]
I added this into my pod file. -> pod install.

When i run the app ->

ld: library not found for -lPods-CustomIOSAlertView

**Comment by wimagguc** [comment]
can you share more of your pod file? `pod 'CustomIOSAlertView', '~> 0.9.3'`worked for me just now, but I'm happy to take a look at yours.

**Comment by lupugabriel** [comment]
![screen shot 2015-04-15 at 11 15 01](https://cloud.githubusercontent.com/assets/3657507/7156708/bed560cc-e360-11e4-81c1-635a4ce760d9.png)

Hi there, thank for the answer!

![screen shot 2015-04-15 at 11 15 53](https://cloud.githubusercontent.com/assets/3657507/7156719/e587e2d0-e360-11e4-84b0-3914b8105b55.png)

And the error:

![screen shot 2015-04-15 at 11 17 02](https://cloud.githubusercontent.com/assets/3657507/7156731/fcf05150-e360-11e4-8691-b3a26465ef06.png)

**Comment by lupugabriel** [comment]
![screen shot 2015-04-15 at 11 17 56](https://cloud.githubusercontent.com/assets/3657507/7156745/17f5883a-e361-11e4-98b4-e77bc9ab6300.png)

**Comment by wimagguc** [comment]
are you opening the project with `$ open Sell\ It.xcworkspace`? Did it work before you added CustomIOSAlertView? What happens if you remove just that one line?

**Comment by lupugabriel** [comment]
Hello, i solved the problem yesterday. It was because of other pods: Nimbus. But the error was saying that it was because CustomIOSAlertView.

Thank you for support!

**Comment by wimagguc** [comment]
awesome :) thanks!
