### ISSUE TITLE
Alert disappears when a keyboard is presented in iOS 8 (landscape)

### ISSUE THREAD

**Issue by oscarfung** [wimagguc/ios-custom-alertview#70]
Hi,

I tried to add a UITextView to the custom alert, but the alert will disappear when the keyboard is presented in iOS 8, landscape mode. I fix this issue by modifying the method -keyboardWillShow:

    UIInterfaceOrientation interfaceOrientation = [[UIApplication sharedApplication] statusBarOrientation];
    if (UIInterfaceOrientationIsLandscape(interfaceOrientation)  && NSFoundationVersionNumber <= NSFoundationVersionNumber_iOS_7_1) {
        CGFloat tmp = keyboardSize.height;
        keyboardSize.height = keyboardSize.width;
        keyboardSize.width = tmp;
    }

Since iOS 8 will return the correct frame in landscape mode, we don't need to exchange its width and height. I add one more condition NSFoundationVersionNumber <= NSFoundationVersionNumber_iOS_7_1 to resolve this issue.

**Comment by wimagguc** [comment]
awesome, thanks! do you mind adding a pull request?

**Comment by oscarfung** [comment]
I will add a pull request, thanks!

**Comment by oscarfung** [comment]
Please check the pull request: https://github.com/wimagguc/ios-custom-alertview/pull/71

**Comment by wimagguc** [comment]
thanks @oscarfung, this is merged now :)
