### ISSUE TITLE
Resizeable iPhone width issue.

### ISSUE THREAD

**Issue by Jules2010** [wimagguc/ios-custom-alertview#78]
I've been playing around with the resizeable iPhone (iOS 8.3) and I've set the width to 320 and height to 800, with xcode 6. I set these values before launching the app.

The width customalertview uses doesn't conform to those set for the resizeable iphone!

I have a picker and some labels views added to the the alertview.
Initially I thought as I hadn't set the width of my picker view that this was pushing the width of the alertview.

However, the alertview sets the width of the device without the resizeable width.
As I have pod files setup, I wasn't able to step through to find the exact code causing this.

Can you have a look at this please?

**Comment by boeung** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

boeung@naver.com 님께 보내신 메일 <[ios-custom-alertview] Resizeable iPhone width issue. (#78)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Jules2010** [comment]
Maybe this is still a problem with the simulator, I'm unable to test this on a device as this size.

http://www.openradar.appspot.com/18209051

**Comment by boeung** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

boeung@naver.com 님께 보내신 메일 <Re: [ios-custom-alertview] Resizeable iPhone width issue. (#78)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Jules2010** [comment]
Ahh nevermind, don't think we need to worry.... http://stackoverflow.com/questions/26228936/resizable-simulator-with-various-screen-sizes
