### ISSUE TITLE
The backgroundColor of the alertView

### ISSUE THREAD

**Issue by iamjjh** [wimagguc/ios-custom-alertview#80]
Hello,
When I set 
    demoView.backgroundColor = [UIColor whiteColor];
It become like this picture
<img width="306" alt="qq20150804-1 2x" src="https://cloud.githubusercontent.com/assets/10794256/9051203/e9258ef8-3a89-11e5-9be3-c9c0ad248e65.png">
if I want to change the view and buttonview backgroundColor, what should I do?

**Comment by tanranran** [comment]
+1

**Comment by quetool** [comment]
if you want to change the backgroundcolor of the entire alert you have to edit the CustomIOSAlertView.m

in -(UIVIew *)createContainerView look for

gradient.colors = [NSArray arrayWithObjects:
                       (id)[[UIColor colorWithRed:255.0/255.0 green:255.0/255.0 blue:255.0/255.0 alpha:1.0f] CGColor],
                       (id)[[UIColor colorWithRed:255.0/255.0 green:255.0/255.0 blue:255.0/255.0 alpha:1.0f] CGColor],
                       (id)[[UIColor colorWithRed:255.0/255.0 green:255.0/255.0 blue:255.0/255.0 alpha:1.0f] CGColor],
                       nil];

**Comment by iamjjh** [comment]
thanks!
