### ISSUE TITLE
may crash

### ISSUE THREAD

**Issue by fengarenas** [wimagguc/ios-custom-alertview#93]
when
 [alertView setDelegate:self];
and not implement
- (void)customIOS7dialogButtonTouchUpInside:(id)alertView clickedButtonAtIndex:(NSInteger)buttonIndex;
it crash

**Comment by wimagguc** [comment]
Yup :)
https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaEncyclopedia/DelegatesandDataSources/DelegatesandDataSources.html
